checks:
    python:
        code_rating: true
        duplicate_code: true
        typecheck_maybe_no_member: true
        classes_valid_slots: true
        basic_missing_reversed_argument: true

build:
    environment:
      python: 3.6.3
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                before:
                    - 'pip install coverage'
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: false
                        coverage:
                            file: '.coverage'
                            config_file: '.coveragerc'
                            format: 'py-cc'
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
    dependency_paths:
        - 'lib/*'