language: python

jobs:
  include:
    - os: linux
      arch: arm64
      python: 3.7
    - os: linux
      arch: ppc64le
      python: 3.7
    - os: osx
      python: 3.6

dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly

notifications:
  email: false

# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then travis_retry pip install cython; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then travis_retry pip install paq lzss; fi
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-test.txt
  - travis_retry python setup.py install

# Run test
script:
  - nosetests --verbose --with-coverage --cover-erase --cover-branches --cover-package=abydos --logging-level=INFO --process-timeout=60 --process-restartworker

# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
