os:
  - linux
  - osx

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

notifications:
  email: false
 
# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 
# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=abydos --logging-level=INFO --processes=1 --process-timeout=60 --process-restartworker
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
