language: python
python:
  - 2.7
  #- pypy
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  #- nightly
  #- pypy3

notifications:
  email: false
 
# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 
# Run test
script:
  - nosetests --with-coverage --cover-branches --cover-package=abydos --logging-level=INFO --processes=1
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
