language: python

python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

notifications:
  email: false

# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install pyliblzma; fi
  - case "$TRAVIS_PYTHON_VERSION" in 3.5|3.6|3.7) travis_retry pip install cython;; esac
  - case "$TRAVIS_PYTHON_VERSION" in 3.5|3.6|3.7) travis_retry pip install paq lzss;; esac
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py install

# Run test
script:
  - nosetests --verbose --with-coverage --cover-erase --cover-branches --cover-package=abydos --logging-level=INFO --process-timeout=60 --process-restartworker

# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
